"""empty message

Revision ID: 8de0c2e0ea5d
Revises: 3b39767bef54
Create Date: 2023-09-04 11:26:04.431695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8de0c2e0ea5d'
down_revision = '3b39767bef54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
                              existing_type=sa.REAL(),
                              type_=sa.Float(precision=2),
                              existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
                              existing_type=sa.Float(precision=2),
                              type_=sa.REAL(),
                              existing_nullable=False)

    op.create_table('spatial_ref_sys',
                    sa.Column('srid', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('auth_name', sa.VARCHAR(length=256),
                              autoincrement=False, nullable=True),
                    sa.Column('auth_srid', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('srtext', sa.VARCHAR(length=2048),
                              autoincrement=False, nullable=True),
                    sa.Column('proj4text', sa.VARCHAR(length=2048),
                              autoincrement=False, nullable=True),
                    sa.CheckConstraint('srid > 0 AND srid <= 998999',
                                       name='spatial_ref_sys_srid_check'),
                    sa.PrimaryKeyConstraint(
                        'srid', name='spatial_ref_sys_pkey')
                    )
    # ### end Alembic commands ###
